### PR TITLE
Upgrade to InfluxDB v2

### PR DESCRIPTION
**Pull request by Konnichy**
Hello,

Although this is my first encounter with Go, I thought I'd still try to upgrade the InfluxDB v2. It's was not very complicated and I wish to share my work with you.

I modified everything (code, documentation, tests, Grafana provisioning), although I'm not sure about tests.

What do you think about it?

### CODE REVIEW

**Comment by eargollo** [comment]
Thanks for the contribution. I did hit a wall with Influx2 at first and decided to come back later because I was in a hurry to get Grafana going. 

I will test it and let you know.

Since this is a change that breaks backward compatibility, I think we need to support both Influx versions for a while. Adding an `influxversion` with v1 as default seems to be a good idea.

**Comment by eargollo** [comment]
We actually could infer the expected Influx version based on the configuration.

**Comment by Konnichy** [comment]
Either that, or write a migration script.

Maybe support both version could be better, since the same question will raise about InfluxDB v3, and I personally won't make the switch because this version doesn't support Flux queries anymore. Some users may have similar concerns switching from v1 to v2.

**Comment by eargollo** [comment]
Agree that version is better to pave the road further. I also think a migration script is a good idea. I have a lot of historical data in v1 that I would love to bring to v2.

**Comment by Konnichy** [comment]
Apparently, InfluxDB v2 Docker images automatically upgrade v1 databases if additional environment variables are correctly configured.
Another solution I found in my old notes would be to manually launch the upgrade with a single command such as:
`influxd upgrade --v1-dir /var/lib/influxdb --v2-config-path ~/influxdbv2.conf --username <USERNAME> --password '<PASSWORD_HERE>' --org mYSTERY --bucket default --retention 0`

All the official information can be found [here](https://docs.influxdata.com/influxdb/v2/install/upgrade/v1-to-v2/).

It might be easier to recommend one of these very easy processes and leave the code v2 only, what do you think?

**Comment by eargollo** [comment]
Thank you very much for all the info. With the end of the year rush, I couldn't work with it yet. Hopefully checking it out soon.

**Comment by eargollo** [comment]
Once again thanks for the PR. I have refactored your code to enable support for both InfluxDB v1 and v2. PR: #67 

Tested it with both and code worked fine. I will publish an upgrade guide as I upgrade my own setup.

Closing this PR.

**Pull request closed without merging**
